
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

public class Solution {
    public char findTheDifference(String s, String t) {
        //remember (char) int to make 97 -> a
        int[] count = new int[256];
        int i = 0;
        for (i = 0; i < s.length(); i++){
            count[s.charAt(i)]++;
            count[t.charAt(i)]--;
        }
        count[t.charAt(i)]--;
        for (int j = 0; j < 256; j++){
            if (count[j] != 0) return (char) j;
        }
        return '0';
    }
}
